version: "3"
services:
  synchronization-back:
    image: synchronization-back
    build:
      dockerfile: Dockerfile
      context: ./drive-sync
    container_name: synchronization-back
    env_file:
      - drive-sync/src/main/resources/.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
  synchronization-bot:
    image: synchronization-bot
    build:
      dockerfile: Dockerfile
      context: ./image-drive-bot
    container_name: synchronization-bot
    env_file:
      - image-drive-bot/src/main/resources/.env
    depends_on:
      - synchronization-back
  postgres-db:
    image: postgres
    env_file:
      - drive-sync/src/main/resources/.env
    ports:
      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data




